name: Non-Main

on:
  push:
    branches-ignore: 
      - main

jobs:
  plan:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: marceloprado/has-changed-path@master
        id: changed-terraform
        with:
          paths: terraform/

      - name: Terraform Plan
        if: steps.changed-terraform.outputs.changed == 'true'
        id: terraform-plan
        uses: ./.github/actions/terraform_plan
        env:
          TF_VAR_aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
